"""completion time

Revision ID: 44e0e98263b6
Revises: 981ba70c46c4
Create Date: 2020-05-07 10:59:21.544454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e0e98263b6'
down_revision = '981ba70c46c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('completion_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_item_completion_time'), 'item', ['completion_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_completion_time'), table_name='item')
    op.drop_column('item', 'completion_time')
    # ### end Alembic commands ###
