"""Added completion status to items

Revision ID: 981ba70c46c4
Revises: fb5049a33984
Create Date: 2020-03-18 10:28:05.693395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981ba70c46c4'
down_revision = 'fb5049a33984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('completion_status', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_item_completion_status'), 'item', ['completion_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_completion_status'), table_name='item')
    op.drop_column('item', 'completion_status')
    # ### end Alembic commands ###
